/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package net.mcreator.solomon;

import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.common.registry.EntityEntry;
import net.minecraftforge.fml.common.network.simpleimpl.IMessageHandler;
import net.minecraftforge.fml.common.network.simpleimpl.IMessage;
import net.minecraftforge.fml.common.network.IGuiHandler;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.discovery.ASMDataTable;
import net.minecraftforge.fml.common.IWorldGenerator;
import net.minecraftforge.fml.common.IFuelHandler;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.client.event.ModelRegistryEvent;

import net.minecraft.world.storage.WorldSavedData;
import net.minecraft.world.gen.IChunkGenerator;
import net.minecraft.world.chunk.IChunkProvider;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.World;
import net.minecraft.util.ResourceLocation;
import net.minecraft.potion.Potion;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Item;
import net.minecraft.entity.player.EntityPlayerMP;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.block.Block;

import net.mcreator.solomon.gui.GuiZhaohuangui;
import net.mcreator.solomon.gui.GuiVisionset;
import net.mcreator.solomon.gui.GuiVisionhui;
import net.mcreator.solomon.gui.GuiUpdagui;
import net.mcreator.solomon.gui.GuiShouce;
import net.mcreator.solomon.gui.GuiShenkafng;
import net.mcreator.solomon.gui.GuiSamelwen;
import net.mcreator.solomon.gui.GuiMamonwen;
import net.mcreator.solomon.gui.GuiLvrens;
import net.mcreator.solomon.gui.GuiLuciwens;
import net.mcreator.solomon.gui.GuiLinajiunc;
import net.mcreator.solomon.gui.GuiLeviaswen;
import net.mcreator.solomon.gui.GuiJuhe;
import net.mcreator.solomon.gui.GuiDuanzao;
import net.mcreator.solomon.gui.GuiBelwen;
import net.mcreator.solomon.gui.GuiBelpwen;
import net.mcreator.solomon.gui.GuiBackdoo;
import net.mcreator.solomon.gui.GuiAsmodwenxian;

import java.util.function.Supplier;
import java.util.Random;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class ElementsSolomonMod implements IFuelHandler, IWorldGenerator {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<Biome>> biomes = new ArrayList<>();
	public final List<Supplier<EntityEntry>> entities = new ArrayList<>();
	public final List<Supplier<Potion>> potions = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();
	public ElementsSolomonMod() {
		sounds.put(new ResourceLocation("solomon", "asmodji1"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "asmodji1")));
		sounds.put(new ResourceLocation("solomon", "asmodji2"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "asmodji2")));
		sounds.put(new ResourceLocation("solomon", "asmodda"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "asmodda")));
		sounds.put(new ResourceLocation("solomon", "bsstjineng"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "bsstjineng")));
		sounds.put(new ResourceLocation("solomon", "beelji1"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "beelji1")));
		sounds.put(new ResourceLocation("solomon", "beelji2"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "beelji2")));
		sounds.put(new ResourceLocation("solomon", "beelji3"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "beelji3")));
		sounds.put(new ResourceLocation("solomon", "beelda"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "beelda")));
		sounds.put(new ResourceLocation("solomon", "bsstdie"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "bsstdie")));
		sounds.put(new ResourceLocation("solomon", "tlstjineng"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "tlstjineng")));
		sounds.put(new ResourceLocation("solomon", "tlstdeath"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "tlstdeath")));
		sounds.put(new ResourceLocation("solomon", "mammonji1"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "mammonji1")));
		sounds.put(new ResourceLocation("solomon", "mammonji2"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "mammonji2")));
		sounds.put(new ResourceLocation("solomon", "mammonda"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "mammonda")));
		sounds.put(new ResourceLocation("solomon", "seyujineng"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "seyujineng")));
		sounds.put(new ResourceLocation("solomon", "seyudeath2"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "seyudeath2")));
		sounds.put(new ResourceLocation("solomon", "seyudeath01"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "seyudeath01")));
		sounds.put(new ResourceLocation("solomon", "planetbefall_2"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "planetbefall_2")));
		sounds.put(new ResourceLocation("solomon", "planerbefall_3"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "planerbefall_3")));
		sounds.put(new ResourceLocation("solomon", "planetbefall_1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "planetbefall_1")));
		sounds.put(new ResourceLocation("solomon", "qianzao_1"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "qianzao_1")));
		sounds.put(new ResourceLocation("solomon", "qianzao_2"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "qianzao_2")));
		sounds.put(new ResourceLocation("solomon", "qianzao_3"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "qianzao_3")));
		sounds.put(new ResourceLocation("solomon", "yvzhang_1"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "yvzhang_1")));
		sounds.put(new ResourceLocation("solomon", "yvzhang_2"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "yvzhang_2")));
		sounds.put(new ResourceLocation("solomon", "yvzhang_3"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "yvzhang_3")));
		sounds.put(new ResourceLocation("solomon", "liming1"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "liming1")));
		sounds.put(new ResourceLocation("solomon", "liming2"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "liming2")));
		sounds.put(new ResourceLocation("solomon", "liming3"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "liming3")));
		sounds.put(new ResourceLocation("solomon", "zhishi1"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "zhishi1")));
		sounds.put(new ResourceLocation("solomon", "zhishi2"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "zhishi2")));
		sounds.put(new ResourceLocation("solomon", "landuoji"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "landuoji")));
		sounds.put(new ResourceLocation("solomon", "landuodea"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "landuodea")));
		sounds.put(new ResourceLocation("solomon", "belphji1"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "belphji1")));
		sounds.put(new ResourceLocation("solomon", "belphji2"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "belphji2")));
		sounds.put(new ResourceLocation("solomon", "belphda"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "belphda")));
		sounds.put(new ResourceLocation("solomon", "bnstji"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "bnstji")));
		sounds.put(new ResourceLocation("solomon", "bnstdea"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "bnstdea")));
		sounds.put(new ResourceLocation("solomon", "samji1"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "samji1")));
		sounds.put(new ResourceLocation("solomon", "samji2"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "samji2")));
		sounds.put(new ResourceLocation("solomon", "samda"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "samda")));
		sounds.put(new ResourceLocation("solomon", "tianjie1"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "tianjie1")));
		sounds.put(new ResourceLocation("solomon", "tianjie2"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "tianjie2")));
		sounds.put(new ResourceLocation("solomon", "tianjie3"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "tianjie3")));
		sounds.put(new ResourceLocation("solomon", "xuanji1"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "xuanji1")));
		sounds.put(new ResourceLocation("solomon", "xuanji2"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "xuanji2")));
		sounds.put(new ResourceLocation("solomon", "xuanji3"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "xuanji3")));
		sounds.put(new ResourceLocation("solomon", "jdstji"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "jdstji")));
		sounds.put(new ResourceLocation("solomon", "jdstdea"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "jdstdea")));
		sounds.put(new ResourceLocation("solomon", "leviaji1"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "leviaji1")));
		sounds.put(new ResourceLocation("solomon", "leviaji2"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "leviaji2")));
		sounds.put(new ResourceLocation("solomon", "leviada"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "leviada")));
		sounds.put(new ResourceLocation("solomon", "jdzjji1"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "jdzjji1")));
		sounds.put(new ResourceLocation("solomon", "jdzjji2"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "jdzjji2")));
		sounds.put(new ResourceLocation("solomon", "amstji"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "amstji")));
		sounds.put(new ResourceLocation("solomon", "amstdea"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "amstdea")));
		sounds.put(new ResourceLocation("solomon", "amzjji1"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "amzjji1")));
		sounds.put(new ResourceLocation("solomon", "amzjji2"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "amzjji2")));
		sounds.put(new ResourceLocation("solomon", "luciji1"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "luciji1")));
		sounds.put(new ResourceLocation("solomon", "luciji2"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "luciji2")));
		sounds.put(new ResourceLocation("solomon", "lucida"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "lucida")));
		sounds.put(new ResourceLocation("solomon", "meimiao1"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "meimiao1")));
		sounds.put(new ResourceLocation("solomon", "meimiao2"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "meimiao2")));
		sounds.put(new ResourceLocation("solomon", "meimiao3"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "meimiao3")));
		sounds.put(new ResourceLocation("solomon", "yaeji1"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "yaeji1")));
		sounds.put(new ResourceLocation("solomon", "yaeji2"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "yaeji2")));
		sounds.put(new ResourceLocation("solomon", "yaeji3"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "yaeji3")));
		sounds.put(new ResourceLocation("solomon", "yaeda1"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "yaeda1")));
		sounds.put(new ResourceLocation("solomon", "yaeda2"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "yaeda2")));
		sounds.put(new ResourceLocation("solomon", "yaeda3"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "yaeda3")));
		sounds.put(new ResourceLocation("solomon", "eyao1"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "eyao1")));
		sounds.put(new ResourceLocation("solomon", "eyao2"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "eyao2")));
		sounds.put(new ResourceLocation("solomon", "eyao3"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "eyao3")));
		sounds.put(new ResourceLocation("solomon", "shoatt"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "shoatt")));
		sounds.put(new ResourceLocation("solomon", "shoda"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "shoda")));
		sounds.put(new ResourceLocation("solomon", "zhongliskill"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "zhongliskill")));
		sounds.put(new ResourceLocation("solomon", "zhongliatk"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "zhongliatk")));
		sounds.put(new ResourceLocation("solomon", "zhonglida"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "zhonglida")));
		sounds.put(new ResourceLocation("solomon", "childea1"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "childea1")));
		sounds.put(new ResourceLocation("solomon", "childep2a"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "childep2a")));
		sounds.put(new ResourceLocation("solomon", "childep1da"), new net.minecraft.util.SoundEvent(new ResourceLocation("solomon", "childep1da")));
	}

	public void preInit(FMLPreInitializationEvent event) {
		try {
			for (ASMDataTable.ASMData asmData : event.getAsmData().getAll(ModElement.Tag.class.getName())) {
				Class<?> clazz = Class.forName(asmData.getClassName());
				if (clazz.getSuperclass() == ElementsSolomonMod.ModElement.class)
					elements.add((ElementsSolomonMod.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(ElementsSolomonMod.ModElement::initElements);
		this.addNetworkMessage(SolomonModVariables.WorldSavedDataSyncMessageHandler.class, SolomonModVariables.WorldSavedDataSyncMessage.class,
				Side.SERVER, Side.CLIENT);
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}

	@Override
	public void generate(Random random, int chunkX, int chunkZ, World world, IChunkGenerator cg, IChunkProvider cp) {
		elements.forEach(element -> element.generateWorld(random, chunkX * 16, chunkZ * 16, world, world.provider.getDimension(), cg, cp));
	}

	@Override
	public int getBurnTime(ItemStack fuel) {
		for (ModElement element : elements) {
			int ret = element.addFuel(fuel);
			if (ret != 0)
				return ret;
		}
		return 0;
	}

	@SubscribeEvent
	public void onPlayerLoggedIn(net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerLoggedInEvent event) {
		if (!event.player.world.isRemote) {
			WorldSavedData mapdata = SolomonModVariables.MapVariables.get(event.player.world);
			WorldSavedData worlddata = SolomonModVariables.WorldVariables.get(event.player.world);
			if (mapdata != null)
				SolomonMod.PACKET_HANDLER.sendTo(new SolomonModVariables.WorldSavedDataSyncMessage(0, mapdata), (EntityPlayerMP) event.player);
			if (worlddata != null)
				SolomonMod.PACKET_HANDLER.sendTo(new SolomonModVariables.WorldSavedDataSyncMessage(1, worlddata), (EntityPlayerMP) event.player);
		}
	}

	@SubscribeEvent
	public void onPlayerChangedDimension(net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerChangedDimensionEvent event) {
		if (!event.player.world.isRemote) {
			WorldSavedData worlddata = SolomonModVariables.WorldVariables.get(event.player.world);
			if (worlddata != null)
				SolomonMod.PACKET_HANDLER.sendTo(new SolomonModVariables.WorldSavedDataSyncMessage(1, worlddata), (EntityPlayerMP) event.player);
		}
	}
	private int messageID = 0;
	public <T extends IMessage, V extends IMessage> void addNetworkMessage(Class<? extends IMessageHandler<T, V>> handler, Class<T> messageClass,
			Side... sides) {
		for (Side side : sides)
			SolomonMod.PACKET_HANDLER.registerMessage(handler, messageClass, messageID, side);
		messageID++;
	}
	public static class GuiHandler implements IGuiHandler {
		@Override
		public Object getServerGuiElement(int id, EntityPlayer player, World world, int x, int y, int z) {
			if (id == GuiSamelwen.GUIID)
				return new GuiSamelwen.GuiContainerMod(world, x, y, z, player);
			if (id == GuiJuhe.GUIID)
				return new GuiJuhe.GuiContainerMod(world, x, y, z, player);
			if (id == GuiDuanzao.GUIID)
				return new GuiDuanzao.GuiContainerMod(world, x, y, z, player);
			if (id == GuiLinajiunc.GUIID)
				return new GuiLinajiunc.GuiContainerMod(world, x, y, z, player);
			if (id == GuiLvrens.GUIID)
				return new GuiLvrens.GuiContainerMod(world, x, y, z, player);
			if (id == GuiUpdagui.GUIID)
				return new GuiUpdagui.GuiContainerMod(world, x, y, z, player);
			if (id == GuiAsmodwenxian.GUIID)
				return new GuiAsmodwenxian.GuiContainerMod(world, x, y, z, player);
			if (id == GuiZhaohuangui.GUIID)
				return new GuiZhaohuangui.GuiContainerMod(world, x, y, z, player);
			if (id == GuiBelwen.GUIID)
				return new GuiBelwen.GuiContainerMod(world, x, y, z, player);
			if (id == GuiShouce.GUIID)
				return new GuiShouce.GuiContainerMod(world, x, y, z, player);
			if (id == GuiMamonwen.GUIID)
				return new GuiMamonwen.GuiContainerMod(world, x, y, z, player);
			if (id == GuiBackdoo.GUIID)
				return new GuiBackdoo.GuiContainerMod(world, x, y, z, player);
			if (id == GuiShenkafng.GUIID)
				return new GuiShenkafng.GuiContainerMod(world, x, y, z, player);
			if (id == GuiVisionset.GUIID)
				return new GuiVisionset.GuiContainerMod(world, x, y, z, player);
			if (id == GuiBelpwen.GUIID)
				return new GuiBelpwen.GuiContainerMod(world, x, y, z, player);
			if (id == GuiLeviaswen.GUIID)
				return new GuiLeviaswen.GuiContainerMod(world, x, y, z, player);
			if (id == GuiVisionhui.GUIID)
				return new GuiVisionhui.GuiContainerMod(world, x, y, z, player);
			if (id == GuiLuciwens.GUIID)
				return new GuiLuciwens.GuiContainerMod(world, x, y, z, player);
			return null;
		}

		@Override
		public Object getClientGuiElement(int id, EntityPlayer player, World world, int x, int y, int z) {
			if (id == GuiSamelwen.GUIID)
				return new GuiSamelwen.GuiWindow(world, x, y, z, player);
			if (id == GuiJuhe.GUIID)
				return new GuiJuhe.GuiWindow(world, x, y, z, player);
			if (id == GuiDuanzao.GUIID)
				return new GuiDuanzao.GuiWindow(world, x, y, z, player);
			if (id == GuiLinajiunc.GUIID)
				return new GuiLinajiunc.GuiWindow(world, x, y, z, player);
			if (id == GuiLvrens.GUIID)
				return new GuiLvrens.GuiWindow(world, x, y, z, player);
			if (id == GuiUpdagui.GUIID)
				return new GuiUpdagui.GuiWindow(world, x, y, z, player);
			if (id == GuiAsmodwenxian.GUIID)
				return new GuiAsmodwenxian.GuiWindow(world, x, y, z, player);
			if (id == GuiZhaohuangui.GUIID)
				return new GuiZhaohuangui.GuiWindow(world, x, y, z, player);
			if (id == GuiBelwen.GUIID)
				return new GuiBelwen.GuiWindow(world, x, y, z, player);
			if (id == GuiShouce.GUIID)
				return new GuiShouce.GuiWindow(world, x, y, z, player);
			if (id == GuiMamonwen.GUIID)
				return new GuiMamonwen.GuiWindow(world, x, y, z, player);
			if (id == GuiBackdoo.GUIID)
				return new GuiBackdoo.GuiWindow(world, x, y, z, player);
			if (id == GuiShenkafng.GUIID)
				return new GuiShenkafng.GuiWindow(world, x, y, z, player);
			if (id == GuiVisionset.GUIID)
				return new GuiVisionset.GuiWindow(world, x, y, z, player);
			if (id == GuiBelpwen.GUIID)
				return new GuiBelpwen.GuiWindow(world, x, y, z, player);
			if (id == GuiLeviaswen.GUIID)
				return new GuiLeviaswen.GuiWindow(world, x, y, z, player);
			if (id == GuiVisionhui.GUIID)
				return new GuiVisionhui.GuiWindow(world, x, y, z, player);
			if (id == GuiLuciwens.GUIID)
				return new GuiLuciwens.GuiWindow(world, x, y, z, player);
			return null;
		}
	}
	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<Biome>> getBiomes() {
		return biomes;
	}

	public List<Supplier<EntityEntry>> getEntities() {
		return entities;
	}

	public List<Supplier<Potion>> getPotions() {
		return potions;
	}
	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}
		protected final ElementsSolomonMod elements;
		protected final int sortid;
		public ModElement(ElementsSolomonMod elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLInitializationEvent event) {
		}

		public void preInit(FMLPreInitializationEvent event) {
		}

		public void generateWorld(Random random, int posX, int posZ, World world, int dimID, IChunkGenerator cg, IChunkProvider cp) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		public void registerModels(ModelRegistryEvent event) {
		}

		public int addFuel(ItemStack fuel) {
			return 0;
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
